# =============================================
# Auth Service specific values
# =============================================

name: auth-service
replicaCount: 2

image:
  repository: acrmicroservicesdev17e706.azurecr.io/auth-service
  tag: v1

containerPort: 5001

service:
  type: ClusterIP
  port: 5001